services:
  backend:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: customer-service-bot
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./src:/app/src
   